### ISSUE TITLE
Incorrect Calibration for Ego RGB Camera in `fair_cooking_06_4` Take

### ISSUE THREAD

**Issue by m43** [facebookresearch/Ego4d#365]
The ego RGB camera in the `fair_cooking_06_4` take (UUID: `a261cc1d-7a45-479f-81a9-7c73eb379e6c`) has incorrect calibration parameters when using the `aria01_noimagestreams.vrs` file. The calibration data for the camera does not undistort the images correctly and mismatches the resolution of the image stream and `frame_aligned_videos`:
```py
from projectaria_tools.core import calibration
from projectaria_tools.core import data_provider

release_dir = "./datasets/egoexo4d"
take_name = "fair_cooking_06_4"

aria_dir = os.path.join(release_dir, take["root_dir"])
aria_path = os.path.join(aria_dir, f"aria01_noimagestreams.vrs")
vrs_data_provider = data_provider.create_vrs_data_provider(aria_path)

device_calib = vrs_data_provider.get_device_calibration()
src_calib = device_calib.get_camera_calib("camera-rgb")

print(src_calib)
```
```yaml
CameraCalibration(
    label: camera-rgb,
    model name: Fisheye624,
    principal point: [1454.95, 1456.37],
    focal length: [1221.64, 1221.64],
    projection params: [1221.64, 1454.95, 1456.37, 0.385091, -0.317651, -0.34768, 1.87269, -2.19933, 0.780143, -0.00108388, -0.000392366, 0.00125706, -8.63757e-05, 6.62793e-05, -0.000117569],
    image size (w,h): [2880, 2880],
    T_Device_Camera: (translation:[-0.00443885, -0.0119854, -0.00508963],
    quaternion(x,y,z,w): [0.333491, 0.0418546, 0.0357579, 0.941145]),
    serialNumber: 0450577b730411674401100000000000
)
```

Using `aria01.vrs` instead provides a calibration that matches the expected 1408x1408 resolution of the image stream and produces correct undistortion results:
```py
aria_path = os.path.join(aria_dir, f"aria01.vrs")
vrs_data_provider = data_provider.create_vrs_data_provider(aria_path)

device_calib = vrs_data_provider.get_device_calibration()
src_calib = device_calib.get_camera_calib("camera-rgb")

print(src_calib)
```
```yaml
CameraCalibration(
    label: camera-rgb,
    model name: Fisheye624,
    principal point: [711.224, 711.937],
    focal length: [610.819, 610.819],
    projection params: [610.819, 711.224, 711.937, 0.385091, -0.317651, -0.34768, 1.87269, -2.19933, 0.780143, -0.00108388, -0.000392366, 0.00125706, -8.63757e-05, 6.62793e-05, -0.000117569],
    image size (w,h): [1408, 1408],
    T_Device_Camera: (translation:[-0.00443885, -0.0119854, -0.00508963],
    quaternion(x,y,z,w): [0.333491, 0.0418546, 0.0357579, 0.941145]),
    serialNumber: 0450577b730411674401100000000000
)
```

When used with the common undistortion pipeline, the two calibrations give the following results:
```py
...
dst_calib = calibration.get_linear_camera_calibration(512, 512, 150)
img = cv2.rotate(img, cv2.ROTATE_90_COUNTERCLOCKWISE)
undistorted_img = calibration.distort_by_calibration(img, dst_calib, src_calib)
undistorted_img = cv2.rotate(undistorted_img, cv2.ROTATE_90_CLOCKWISE)
...
```
<table>
  <tr>
    <th>Distorted Image</th>
    <th>Undistorted Image (`aria01_noimagestreams.vrs`)</th>
    <th>Undistorted Image (`aria01.vrs`)</th>
  </tr>
  <tr>
    <td><img src="https://github.com/user-attachments/assets/8cd92a74-fb10-445a-9269-bdcb7136510c" width="300"></td>
    <td><img src="https://github.com/user-attachments/assets/bf9a7f20-a655-4aaa-9175-962686b9bb18" width="300"></td>
    <td><img src="https://github.com/user-attachments/assets/941e8847-eadf-4669-8b18-f697c7e255d7" width="300"></td>
  </tr>
</table>
